<a href="https://colab.research.google.com/github/FranciaAlday/Proyectos/blob/main/PPCienciaDatos/Clases/18AgoPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DataFrames

Pandas es una biblioteca para uso "sencillo" de Dataframes

Matplotlib para gráficas, las demás bibliotecas de gráficas están basadas en este

In [ ]:
import pandas as pd

In [ ]:
datos = pd.read_csv('https://bit.ly/31B56KB')
type(datos)

pandas.core.frame.DataFrame

In [ ]:
datos.head()

Contaminacion_SO2  Temperatura  Fabricas  Habitantes  Velocidad_viento  \
0                 10         70.3       213         582               6.0   
1                 13         61.0        91         132               8.2   
2                 12         56.7       453         716               8.7   
3                 17         51.9       454         515               9.0   
4                 56         49.1       412         158               9.0   

   Lluvia  Dias_Lluvia  
0    7.05           36  
1   48.52          100  
2   20.66           67  
3   12.95           86  
4   43.37          127

In [ ]:
datos.tail()

Contaminacion_SO2  Temperatura  Fabricas  Habitantes  Velocidad_viento  \
36                 31         59.3        96         308              10.6   
37                 26         57.8       197         299               7.6   
38                 29         51.1       379         531               9.4   
39                 31         55.2        35          71               6.5   
40                 16         45.7       569         717              11.8   

    Lluvia  Dias_Lluvia  
36   44.68          116  
37   42.59          115  
38   38.79          164  
39   40.75          148  
40   29.07          123

In [ ]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Contaminacion_SO2  41 non-null     int64  
 1   Temperatura        41 non-null     float64
 2   Fabricas           41 non-null     int64  
 3   Habitantes         41 non-null     int64  
 4   Velocidad_viento   41 non-null     float64
 5   Lluvia             41 non-null     float64
 6   Dias_Lluvia        41 non-null     int64  
dtypes: float64(3), int64(4)
memory usage: 2.4 KB


In [ ]:
datos.describe()

Contaminacion_SO2  Temperatura     Fabricas   Habitantes  \
count          41.000000    41.000000    41.000000    41.000000   
mean           30.048780    55.763415   463.097561   608.609756   
std            23.472272     7.227716   563.473948   579.113023   
min             8.000000    43.500000    35.000000    71.000000   
25%            13.000000    50.600000   181.000000   299.000000   
50%            26.000000    54.600000   347.000000   515.000000   
75%            35.000000    59.300000   462.000000   717.000000   
max           110.000000    75.500000  3344.000000  3369.000000   

       Velocidad_viento     Lluvia  Dias_Lluvia  
count         41.000000  41.000000    41.000000  
mean           9.443902  36.769024   113.902439  
std            1.428644  11.771550    26.506419  
min            6.000000   7.050000    36.000000  
25%            8.700000  30.960000   103.000000  
50%            9.300000  38.740000   115.000000  
75%           10.600000  43.110000   128.000000  
max           12.700000  59.800000   166.000000

In [ ]:
#nos dice el total de las filas del dataframe
len(datos)

41

In [ ]:
#nombres de las columnas
datos.columns

Index(['Contaminacion_SO2', 'Temperatura', 'Fabricas', 'Habitantes',
       'Velocidad_viento', 'Lluvia', 'Dias_Lluvia'],
      dtype='object')

In [ ]:
datos.columns[0]

'Contaminacion_SO2'

In [ ]:
#tipo de datos
datos.dtypes

Contaminacion_SO2      int64
Temperatura          float64
Fabricas               int64
Habitantes             int64
Velocidad_viento     float64
Lluvia               float64
Dias_Lluvia            int64
dtype: object

In [ ]:
datos.shape

(41, 7)

In [ ]:
# es un atributo, no un método. values nos regresa un arreglo de numpy
datos.values

array([[  10.  ,   70.3 ,  213.  ,  582.  ,    6.  ,    7.05,   36.  ],
       [  13.  ,   61.  ,   91.  ,  132.  ,    8.2 ,   48.52,  100.  ],
       [  12.  ,   56.7 ,  453.  ,  716.  ,    8.7 ,   20.66,   67.  ],
       [  17.  ,   51.9 ,  454.  ,  515.  ,    9.  ,   12.95,   86.  ],
       [  56.  ,   49.1 ,  412.  ,  158.  ,    9.  ,   43.37,  127.  ],
       [  36.  ,   54.  ,   80.  ,   80.  ,    9.  ,   40.25,  114.  ],
       [  29.  ,   57.3 ,  434.  ,  757.  ,    9.3 ,   38.89,  111.  ],
       [  14.  ,   68.4 ,  136.  ,  529.  ,    8.8 ,   54.47,  116.  ],
       [  10.  ,   75.5 ,  207.  ,  335.  ,    9.  ,   59.8 ,  128.  ],
       [  24.  ,   61.5 ,  368.  ,  497.  ,    9.1 ,   48.34,  115.  ],
       [ 110.  ,   50.6 , 3344.  , 3369.  ,   10.4 ,   34.44,  122.  ],
       [  28.  ,   52.3 ,  361.  ,  746.  ,    9.7 ,   38.74,  121.  ],
       [  17.  ,   49.  ,  104.  ,  201.  ,   11.2 ,   30.85,  103.  ],
       [   8.  ,   56.6 ,  125.  ,  277.  ,   12.7 ,   30.58,   

In [ ]:
# Forma de acceder a columnas antes. No es recomendable usarlo
datos['Temperatura'].head(3)

0    70.3
1    61.0
2    56.7
Name: Temperatura, dtype: float64

In [ ]:
# Forma actual
datos.Temperatura.head(3)

0    70.3
1    61.0
2    56.7
Name: Temperatura, dtype: float64

# Series

In [ ]:
s = datos.Contaminacion_SO2
type(s)

pandas.core.series.Series

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.values

array([ 10,  13,  12,  17,  56,  36,  29,  14,  10,  24, 110,  28,  17,
         8,  30,   9,  47,  35,  29,  14,  56,  14,  11,  46,  11,  23,
        65,  26,  69,  61,  94,  10,  18,   9,  10,  28,  31,  26,  29,
        31,  16])

In [ ]:
s.describe

<bound method NDFrame.describe of 0      10
1      13
2      12
3      17
4      56
5      36
6      29
7      14
8      10
9      24
10    110
11     28
12     17
13      8
14     30
15      9
16     47
17     35
18     29
19     14
20     56
21     14
22     11
23     46
24     11
25     23
26     65
27     26
28     69
29     61
30     94
31     10
32     18
33      9
34     10
35     28
36     31
37     26
38     29
39     31
40     16
Name: Contaminacion_SO2, dtype: int64>

In [ ]:
s.mean()

30.048780487804876

In [ ]:
s.std()

23.4722721732603

In [ ]:
#para ver valores repetidos
s.unique()

array([ 10,  13,  12,  17,  56,  36,  29,  14,  24, 110,  28,   8,  30,
         9,  47,  35,  11,  46,  23,  65,  26,  69,  61,  94,  18,  31,
        16])

In [ ]:
s.value_counts()

10     4
14     3
29     3
31     2
26     2
11     2
28     2
9      2
17     2
56     2
24     1
23     1
12     1
18     1
94     1
61     1
69     1
65     1
46     1
110    1
35     1
47     1
13     1
30     1
8      1
36     1
16     1
Name: Contaminacion_SO2, dtype: int64

In [ ]:
s.sort_values(ascending=True).head(7)

13     8
33     9
15     9
0     10
34    10
31    10
8     10
Name: Contaminacion_SO2, dtype: int64

## Particiones

In [ ]:
s[8:14]

8      10
9      24
10    110
11     28
12     17
13      8
Name: Contaminacion_SO2, dtype: int64

In [ ]:
datos[8:14]

Contaminacion_SO2  Temperatura  Fabricas  Habitantes  Velocidad_viento  \
8                  10         75.5       207         335               9.0   
9                  24         61.5       368         497               9.1   
10                110         50.6      3344        3369              10.4   
11                 28         52.3       361         746               9.7   
12                 17         49.0       104         201              11.2   
13                  8         56.6       125         277              12.7   

    Lluvia  Dias_Lluvia  
8    59.80          128  
9    48.34          115  
10   34.44          122  
11   38.74          121  
12   30.85          103  
13   30.58           82

In [ ]:
# vamos a usar esto para particiones. Tambien se pueden usar numeros negativos
datos.iloc[3:8,2:6]

Fabricas  Habitantes  Velocidad_viento  Lluvia
3       454         515               9.0   12.95
4       412         158               9.0   43.37
5        80          80               9.0   40.25
6       434         757               9.3   38.89
7       136         529               8.8   54.47

In [ ]:
datos.iloc[3:8,:]

Contaminacion_SO2  Temperatura  Fabricas  Habitantes  Velocidad_viento  \
3                 17         51.9       454         515               9.0   
4                 56         49.1       412         158               9.0   
5                 36         54.0        80          80               9.0   
6                 29         57.3       434         757               9.3   
7                 14         68.4       136         529               8.8   

   Lluvia  Dias_Lluvia  
3   12.95           86  
4   43.37          127  
5   40.25          114  
6   38.89          111  
7   54.47          116

In [ ]:
# Para seleccionar solo algunas columnas
df2 = datos.filter(('Temperatura','Dias_Lluvia'))
df2.head(3)

Temperatura  Dias_Lluvia
0         70.3           36
1         61.0          100
2         56.7           67

In [ ]:
# Para quitar algunas columnas
df3 = datos.drop(['Temperatura','Dias_Lluvia'],axis=1)
df3.head(3)

Contaminacion_SO2  Fabricas  Habitantes  Velocidad_viento  Lluvia
0                 10       213         582               6.0    7.05
1                 13        91         132               8.2   48.52
2                 12       453         716               8.7   20.66

In [ ]:
grupo = datos.Temperatura

In [ ]:
grupo.sum().head(10)

In [ ]:
s_grupo = grupo.sum()
cond = s_grupo.Temperatura >= 65
cond

In [ ]:
s_grupo[cond]