<a href="https://colab.research.google.com/github/FranciaAlday/Proyectos/blob/main/Patrones/Tareas/Tarea_AlgebraLineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nombre del equipo: MichiCoders


Integrantes:

*   Alday Martínez Francia Aide Verenice - 417031233
*   Berrio Mendoza Eileen Bjork - 317108969
*   Sánchez Domínguez Iván Amaury - 416101001
*   Malagón Gasca Miguel Ángel - 318356613





In [ ]:
import numpy as np
from numpy import array
from math import sqrt
import matplotlib.pyplot as plt

# Biblioteca de álgebra lineal de scipy
from scipy import linalg as la

## Transformaciones lineales

Una transformación lineal es una función, la cual toma elementos de un espacio vectorial $V$ (Dominio) y los "transforma" a elementos del espacio vectorial $W$ (Contradominio), i.e:\
Sean V y W espacios vectoriales, tales que existe T transformacion lineal, donde $T:V → W$

### ¿Qué se necesita para que una transformación sea lineal?

Una transformación es lineal cuando cumple con los siguientes 2 puntos:
1. $T(u + v) = T(u) + T(v)$ $∀u ∈ V$  
2. $T(\alpha v) = \alpha T(v)$ $∀u ∈ V$ y $\forall \alpha \in C$

Veamos el siguiente ejemplo: \
Sea $T:  \mathbb{R}^{2} → \mathbb{R}^{3}$ donde
$T \begin{bmatrix}
x\\
y
\end{bmatrix} = \begin{bmatrix}
x + y\\
y \\
2x
\end{bmatrix}$\
¿T es una transformación lineal?\
Sean $v = \begin{bmatrix}
x_{1}\\
y_{1}
\end{bmatrix}$ y $u = \begin{bmatrix}
x_{2}\\
y_{2}
\end{bmatrix}$ tales que
$u + v =
\begin{bmatrix}
x_{1} + x_{2}\\
y_{1} + y_{2}
\end{bmatrix}$ \
$T(u + v) = T
\begin{bmatrix}
x_{1} + x_{2}\\
y_{1} + y_{2}
\end{bmatrix} = \begin{bmatrix}
(x_{1} + x_{2}) + (y_{1} + y_{2})\\
(y_{1} + y_{2})\\
2(x_{1} + x_{2})
\end{bmatrix} =$ ... $= \begin{bmatrix}
x_{1} + y_{1} + x_{2} + y_{2}\\
y_{1} + y_{2}\\
2(x_{1}) + 2(x_{2})
\end{bmatrix} = \begin{bmatrix}
x_{1} + y_{1}\\
y_{1}\\
2x_{1}
\end{bmatrix} + \begin{bmatrix}
x_{2} + y_{2}\\
y_{2}\\
2x_{2}
\end{bmatrix} = T(v) + T(u)$ \
Sea $\alpha \in \mathbb{R}$ \
$T(\alpha u) = T
\begin{bmatrix}
\alpha x\\
\alpha y
\end{bmatrix} = \begin{bmatrix}
\alpha x + \alpha y\\
\alpha y \\
2\alpha x
\end{bmatrix} = \begin{bmatrix}
\alpha (x + y)\\
\alpha (y) \\
\alpha (2x)
\end{bmatrix} = \alpha \begin{bmatrix}
x + y\\
y \\
2x
\end{bmatrix} = \alpha T(u)$ \
$\therefore T$ es lineal

## Ejercicios


### Ejercicio 1


In [ ]:
# Definición de una "transformación" T

def transformacion_t(v_vector: array):
  return np.array([v_vector[0][0] + 3*v_vector[1][0], v_vector[0][0] + 2*v_vector[1][0]])

v_vector = np.array([[4],[7]])
print (transformacion_t(v_vector))
len(v_vector[0])

[25 18]


1

Tomando la definición de la transformación T, realice lo siguiente:
1. ¿Qué transformación describe?

La transformación $T: \mathbb{R}^{2} \rightarrow \mathbb{R}^{2}$ se define como:

$$
T \begin{bmatrix}
x\\
y
\end{bmatrix} = \begin{bmatrix}
x + 3y\\
x + 2y
\end{bmatrix}
$$

2. Demuestre que T es una transformación lineal

Propiedad de Aditividad: $T(u + v) = T(u) + T(v)$

Donde $u$ y $v$ son vectores en $\mathbb{R}^{2}$.

Tomamos dos vectores arbitrarios $u = \begin{bmatrix} u_1 \\ u_2 \end{bmatrix}$ y $v = \begin{bmatrix} v_1 \\ v_2 \end{bmatrix}$.

Ahora, aplicamos la transformación $T$ a $u + v$

$$
T(u + v) = \begin{bmatrix} (u_1 + v_1) + 3(u_2 + v_2) \\ (u_1 + v_1) + 2(u_2 + v_2) \end{bmatrix} = \begin{bmatrix} u_1 + 3u_2 \\ u_1 + 2u_2 \end{bmatrix} + \begin{bmatrix} v_1 + 3v_2 \\ v_1 + 2v_2 \end{bmatrix} = T(u) + T(v)
$$

$T(u + v) = T(u) + T(v)$, lo que cumple con la propiedad de aditividad.

Propiedad de Homogeneidad: $T(cu) = cT(u)$

Donde $c$ es un escalar y $u$ es un vector en $\mathbb{R}^{2}$.

Tomamos un escalar arbitrario $c$ y un vector $u = \begin{bmatrix} u_1 \\ u_2 \end{bmatrix}$. Aplicamos la transformación $T$ a $cu$:

$$
T(cu) = \begin{bmatrix} cu_1 + 3cu_2 \\ cu_1 + 2cu_2 \end{bmatrix}  = c \begin{bmatrix} u_1 + 3u_2 \\ u_1 + 2u_2 \end{bmatrix} = cT(u)
$$


$T(cu) = cT(u)$, lo que cumple con la propiedad de homogeneidad.

Dado que la transformación $T$ cumple con ambas propiedades de aditividad y homogeneidad, podemos concluir que $T$ es una transformación lineal.



##Ejemplo de implementación

In [ ]:
def transformacion_t(v_vector: array):
  return np.array([v_vector[0][0] + v_vector[1][0], v_vector[1][0], 2*v_vector[0][0]])

# Prueba de que funciona
v_vector = np.array([[2],[3]])
print (transformacion_t(v_vector))

[5 3 4]


In [ ]:
def transformacion2_t(v: array, u: array):
  return np.array([v[0][0] + u[0][0] + v[1][0] + u[1][0] , v[1][0] + u[1][0] , 2*(v[0][0] + u[0][0])])

In [ ]:
v = np.array([[1],[2]])
u = np.array([[3],[4]])

print(v)
print(u)

[[1]
 [2]]
[[3]
 [4]]


In [ ]:
print("Transformación v + u : ", transformacion2_t(v,u))
print("Transformación v : ", transformacion_t(v))
print("Transformación u : ", transformacion_t(u))
print("Transformación v + Transformación u : ", transformacion_t(v) + transformacion_t(u))

Transformación v + u :  [10  6  8]
Transformación v :  [3 2 2]
Transformación u :  [7 4 6]
Transformación v + Transformación u :  [10  6  8]


In [ ]:
a = 2
print("a * Transformación u : ", a * transformacion_t(u))

a * Transformación u :  [14  8 12]


In [ ]:
a = 2
def transformacion_at(v_vector: array):
  return np.array([a*v_vector[0][0] + a*v_vector[1][0], a*v_vector[1][0], a*2*v_vector[0][0]])

print("Transformación au : ", transformacion_at(u))

Transformación au :  [14  8 12]


In [ ]:
print("T es una transformación lineal porque se cumple:")
print("T(v+u):", transformacion2_t(v,u), "= T(v) + T(u):", transformacion_t(v) + transformacion_t(u))
print("aT(u):", a * transformacion_t(u),"= T(au):", transformacion_at(u))

T es una transformación lineal porque se cumple:
T(v+u): [10  6  8] = T(v) + T(u): [10  6  8]
aT(u): [14  8 12] = T(au): [14  8 12]


### Ejercicio 2

Sea T una transformación, donde T está descrita de la siguiente forma: \
$T:  \mathbb{R}^{2} → \mathbb{R}^{3}$ donde
$T \begin{bmatrix}
x\\
y
\end{bmatrix} = \begin{bmatrix}
x\\
y \\
2x + 3y
\end{bmatrix}$ \
Realice lo siguiente:
1. La transformación T ¿Es lineal?


Podemos verificar ambas propiedades al mismo tiempo como $T(u + cv) = T(u) + cT(v)$, donde $u$ y $v$ son vectores en $\mathbb{R}^2$ y $c$ es un escalar.

Consideremos $u = \begin{bmatrix} u_1 \\ u_2 \end{bmatrix}$, $v = \begin{bmatrix} v_1 \\ v_2 \end{bmatrix}$, y $c$ como un escalar arbitrario.

Aplicamos la transformación $T$ a $u + cv$:

$$
T(u + cv) = T\left(\begin{bmatrix} u_1 \\ u_2 \end{bmatrix} + c\begin{bmatrix} v_1 \\ v_2 \end{bmatrix}\right) = T\left(\begin{bmatrix} u_1 + cv_1 \\ u_2 + cv_2 \end{bmatrix}\right)
$$


Ahora, aplicamos la definición de $T$:

$$
\begin{bmatrix} u_1 + cv_1 \\ u_2 + cv_2 \\ 2(u_1 + cv_1) + 3(u_2 + cv_2) \end{bmatrix}  = \begin{bmatrix} u_1 \\ u_2 \\ 2u_1 + 3u_2 \end{bmatrix} + c\begin{bmatrix} v_1 \\ v_2 \\ 2v_1 + 3v_2 \end{bmatrix} = T(u) + cT(v)
$$

Por lo que la transformación $T$ es lineal.

2. Defina una función en Python que represente la transformación T y evalue los vectores $v_1$ y $v_2$



In [ ]:
v1 = np.array([[1],[3]])
v2 = np.array([[10],[1]])
a = 3
# Escriba su codigo aqui

def transformacion3_t(v_vector: array):
  return np.array([v_vector[0][0], v_vector[1][0], 2*v_vector[0][0] + 3*v_vector[1][0]])

print(f'T(1,3) = {transformacion3_t(v1)}')
print(f'T(10,1) = {transformacion3_t(v2)}')

T(1,3) = [ 1  3 11]
T(10,1) = [10  1 23]
